# Generated by Django 4.2.28 on 2026-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('completed_late', 'Completed_Late')], default='upcoming', max_length=20)),
                ('points_awarded', models.FloatField(default=0.0)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('description', models.TextField()),
                ('due_data', models.DateField()),
                ('max_points', models.IntegerField(help_text='Points')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
