# Generated by Django 4.2.28 on 2026-03-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('description', models.TextField()),
                ('due_data', models.DateField()),
                ('max_points', models.IntegerField(help_text='Points')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('completed_late', 'Completed_Late')], default='upcoming', max_length=20)),
                ('points_awarded', models.FloatField(default=0.0)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assigments.assigments')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
