# Generated by Django 4.2.28 on 2026-03-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('assigments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigments',
            new_name='Assignments',
        ),
    ]
