# Generated by Django 4.2.28 on 2026-05-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('assigments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='team.team'),
        ),
        migrations.AddField(
            model_name='assignment_submissions',
            name='assigment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assigments.assignments'),
        ),
    ]
