# Generated by Django 4.2.28 on 2026-03-05 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0002_rename_assigments_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='delete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
