# Generated by Django 4.2.28 on 2026-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0003_assignments_create_at_assignments_delete_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submissions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
