# Generated by Django 4.2.28 on 2026-02-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Channel name (e.g., 'general', 'random)", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Channel description', null=True)),
                ('is_private', models.BooleanField(default=False, help_text='IF True, only selected members can access this channel')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Channel Membership',
                'verbose_name_plural': 'Channel MemberShips',
            },
        ),
    ]
