# Generated by Django 4.2.28 on 2026-02-22 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members with access (for private channels only)', related_name='private_channels', through='channels.ChannelMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(help_text='Parent team', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='team.team'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'user'], name='channels_ch_channel_540741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['team'], name='channels_ch_team_id_2c8baf_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['team', 'name'], name='channels_ch_team_id_33e535_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['is_private'], name='channels_ch_is_priv_cd19a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('team', 'name')},
        ),
    ]
