# Generated by Django 4.2.28 on 2026-05-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_channels', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channel',
            new_name='app_channel_team_id_d54ccb_idx',
            old_name='channels_ch_team_id_2c8baf_idx',
        ),
        migrations.RenameIndex(
            model_name='channel',
            new_name='app_channel_team_id_9c8d66_idx',
            old_name='channels_ch_team_id_33e535_idx',
        ),
        migrations.RenameIndex(
            model_name='channel',
            new_name='app_channel_is_priv_ab425b_idx',
            old_name='channels_ch_is_priv_cd19a7_idx',
        ),
        migrations.RenameIndex(
            model_name='channelmembership',
            new_name='app_channel_channel_45ff4c_idx',
            old_name='channels_ch_channel_540741_idx',
        ),
    ]
